Repository viur-framework/viur-shop, pull requests merged in 2024-11, with the labels that each got.

#28 feat: Set Shipping automated
  src/viur/shop/modules/cart.py
  src/viur/shop/skeletons/cart.py
  src/viur/shop/types/__init__.py
  src/viur/shop/types/enums.py
Labels: Priority: Medium

#30 refactor: Refactor order_add/update and add/fix more validation
  src/viur/shop/modules/order.py
Labels: bug(fix), enhancement, component: module

#29 feat: Ensure `OrderSkel` is written in transaction, remove comments and add hooks
  src/viur/shop/modules/api.py
  src/viur/shop/modules/order.py
  src/viur/shop/services/events.py
Labels: enhancement, component: module

#31 feat: Re-Enable address default after core bugfixes
  index.yaml
  src/viur/shop/modules/address.py
Labels: Priority: Low, enhancement, component: module

#32 fix: Set `module` of `article` bone in `CartItemSkel` explicit
  src/viur/shop/shop.py
  src/viur/shop/skeletons/cart.py
Labels: Priority: Critical, bug(fix), component: skeleton

#33 fix: Missing PaymentProvider should cause `ClientError` and not `LookupError`
  src/viur/shop/modules/order.py
Labels: Priority: High, bug(fix), component: module

#37 feat: Add view in `Address` module to see all own addresses
  index.yaml
  src/viur/shop/modules/address.py
Labels: Priority: Low, component: module

#35 feat: Require bones in `AdressSkel`
  src/viur/shop/skeletons/address.py
Labels: Priority: Low, component: skeleton

#39 feat: Implement more Unzer payment providers
  pyproject.toml
  src/viur/shop/data/translations.py
  src/viur/shop/payment_providers/__init__.py
  src/viur/shop/payment_providers/unzer_bancontact.py
Labels: Priority: Medium, component: payment provider

#40 feat: Filter for available payment provider
  src/viur/shop/modules/address.py
  src/viur/shop/modules/order.py
  src/viur/shop/payment_providers/abstract.py
  src/viur/shop/payment_providers/unzer_abstract.py
  src/viur/shop/skeletons/order.py
  src/viur/shop/types/__init__.py
  src/viur/shop/types/results.py
Labels: Priority: Medium, component: module, component: API, component: payment provider

#43 feat: Make `address_type` multiple
  src/viur/shop/modules/address.py
  src/viur/shop/modules/cart.py
  src/viur/shop/modules/order.py
  src/viur/shop/skeletons/address.py
Labels: Priority: Medium, component: skeleton, component: module
